// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFveb70pNyRyVxGjUKECLsrP7Yf4agKzY',
    appId: '1:1000840068209:web:5cd4c2af5ba8e5b1472fd0',
    messagingSenderId: '1000840068209',
    projectId: 'newsapp-3c8e4',
    authDomain: 'newsapp-3c8e4.firebaseapp.com',
    storageBucket: 'newsapp-3c8e4.appspot.com',
    measurementId: 'G-R0SPY1186Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3N4YjaZ4lV8I5Fy4bC-7wp_oR_gqXnEw',
    appId: '1:1000840068209:android:96d414ac77fbeee2472fd0',
    messagingSenderId: '1000840068209',
    projectId: 'newsapp-3c8e4',
    storageBucket: 'newsapp-3c8e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADzQFO_rucgDIaBCSvh2THw-HptMrQUNw',
    appId: '1:1000840068209:ios:c70783273360dc9c472fd0',
    messagingSenderId: '1000840068209',
    projectId: 'newsapp-3c8e4',
    storageBucket: 'newsapp-3c8e4.appspot.com',
    iosClientId: '1000840068209-cla84588qanb85ddvctpmqnbiu91qibe.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADzQFO_rucgDIaBCSvh2THw-HptMrQUNw',
    appId: '1:1000840068209:ios:c70783273360dc9c472fd0',
    messagingSenderId: '1000840068209',
    projectId: 'newsapp-3c8e4',
    storageBucket: 'newsapp-3c8e4.appspot.com',
    iosClientId: '1000840068209-cla84588qanb85ddvctpmqnbiu91qibe.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsapp',
  );
}
